"""PDF report generator for BioLink results."""

from __future__ import annotations

from datetime import datetime

from fpdf import FPDF


def _safe(text: str) -> str:
    """Make text safe for latin-1 PDF encoding."""
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u00b1": "+/-",
        "\u2265": ">=", "\u2264": "<=", "\u2192": "->",
    }
    for char, repl in replacements.items():
        text = text.replace(char, repl)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _mc(pdf: FPDF, w: float, h: float, text: str):
    """Safe multi_cell that resets x position first."""
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(w, h, text)


def generate_pdf(results: list[dict], disease_name: str) -> bytes:
    """Generate a PDF report. Returns bytes for st.download_button."""
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    W = pdf.w - pdf.l_margin - pdf.r_margin  # usable width

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(W, 12, "BioLink Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(W, 8, _safe(f"Disease: {disease_name}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(W, 6, f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(W, 6, f"Total candidates: {len(results)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    _mc(pdf, W, 4,
        "DISCLAIMER: BioLink is a hypothesis-generation tool for research only. "
        "Not medical advice. Consult a qualified physician before considering any treatment.")
    pdf.ln(6)

    # Summary table
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(W, 8, "Drug Candidates", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    col_w = [10, 48, 20, 24, 34, 44]
    headers = ["#", "Drug", "Conf.", "Tier", "FDA Status", "Verdict"]
    pdf.set_font("Helvetica", "B", 8)
    for w, h in zip(col_w, headers):
        pdf.cell(w, 6, h, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    for i, r in enumerate(results, 1):
        ev = r.get("evidence") or {}
        verdict = (ev.get("verdict") or "-").replace("-", " ").title()
        vals = [
            str(i),
            _safe(r["drug"][:24]),
            f"{r.get('proba', 0):.0%}",
            r.get("tier", ""),
            (r.get("fda_status") or "Unknown")[:16],
            verdict[:20],
        ]
        for w, v in zip(col_w, vals):
            pdf.cell(w, 5, v, border=1)
        pdf.ln()

    # TL;DR section
    top_ev = [r for r in results if (r.get("evidence") or {}).get("tldr")][:10]
    if top_ev:
        pdf.ln(6)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(W, 8, "Evidence Summaries", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for r in top_ev:
            ev = r.get("evidence", {})
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(W, 5, _safe(r["drug"]), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 8)
            _mc(pdf, W, 4, _safe(ev.get("tldr", "")))

            pathway = ev.get("pathway")
            if pathway:
                pdf.set_font("Helvetica", "I", 7)
                _mc(pdf, W, 3.5, _safe(f"Pathway: {pathway}"))

            pdf.ln(2)

    # Footer
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 7)
    _mc(pdf, W, 3.5,
        "Generated by BioLink. Predictions are based on knowledge graph AI and should be "
        "treated as hypotheses for further investigation, not clinical recommendations.")

    return pdf.output()
