"""PDF report generator for BioLink results."""

from __future__ import annotations

from datetime import datetime

from fpdf import FPDF


def _safe_text(text: str) -> str:
    """Replace Unicode characters that latin-1 can't encode."""
    replacements = {
        "\u2014": "-",  # em dash
        "\u2013": "-",  # en dash
        "\u2018": "'",  # left single quote
        "\u2019": "'",  # right single quote
        "\u201c": '"',  # left double quote
        "\u201d": '"',  # right double quote
        "\u2026": "...",  # ellipsis
        "\u00b1": "+/-",  # plus-minus
        "\u2265": ">=",  # greater-equal
        "\u2264": "<=",  # less-equal
    }
    for char, repl in replacements.items():
        text = text.replace(char, repl)
    # Strip any remaining non-latin-1 chars
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf(results: list[dict], disease_name: str) -> bytes:
    """
    Generate a PDF report of BioLink drug repurposing results.

    Returns PDF as bytes for st.download_button.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title page ──
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 20, "BioLink", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, "Drug Repurposing Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, _safe_text(f"Disease: {disease_name}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Candidates: {len(results)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(
        0, 5,
        "DISCLAIMER: This report is generated by BioLink, a hypothesis-generation tool for "
        "research purposes only. It is NOT medical advice. Always consult a qualified healthcare "
        "provider before considering any treatment.",
    )
    pdf.ln(10)

    # ── Summary table ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Summary of Candidates", new_x="LMARGIN", new_y="NEXT")

    # Table header
    pdf.set_font("Helvetica", "B", 9)
    col_widths = [12, 50, 22, 25, 35, 46]
    headers = ["#", "Drug", "Confidence", "Tier", "FDA Status", "Verdict"]
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 7, h, border=1)
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 8)
    for i, r in enumerate(results, 1):
        evidence = r.get("evidence", {}) or {}
        verdict = evidence.get("verdict", "-")
        if verdict != "-":
            verdict = verdict.replace("-", " ").title()

        row = [
            str(i),
            r["drug"][:25],
            f"{r.get('proba', 0):.0%}",
            r.get("tier", ""),
            r.get("fda_status", "Unknown") or "Unknown",
            verdict,
        ]
        for w, val in zip(col_widths, row):
            pdf.cell(w, 6, _safe_text(val), border=1)
        pdf.ln()

    # ── Detailed evidence for top results ──
    top_with_evidence = [r for r in results if r.get("evidence", {}).get("summary")][:5]
    if top_with_evidence:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "Detailed Evidence", new_x="LMARGIN", new_y="NEXT")

        for r in top_with_evidence:
            evidence = r.get("evidence", {})
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, _safe_text(f"{r['drug']} ({r.get('proba', 0):.0%} {r.get('tier', '')})"), new_x="LMARGIN", new_y="NEXT")

            # TL;DR
            tldr = evidence.get("tldr")
            if tldr:
                pdf.set_font("Helvetica", "I", 9)
                pdf.multi_cell(0, 5, _safe_text(f"TL;DR: {tldr}"))

            # Summary (truncated)
            summary = evidence.get("summary", "")
            if summary:
                pdf.set_font("Helvetica", "", 8)
                truncated = summary[:500] + ("..." if len(summary) > 500 else "")
                pdf.multi_cell(0, 4, _safe_text(truncated))

            # Citations
            citations = evidence.get("citations", [])
            if citations:
                pdf.set_font("Helvetica", "", 7)
                pdf.cell(0, 5, "Sources:", new_x="LMARGIN", new_y="NEXT")
                for url in citations[:5]:
                    pdf.cell(0, 4, f"  - {url}", new_x="LMARGIN", new_y="NEXT")

            pdf.ln(3)

    # Footer disclaimer on last page
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(
        0, 4,
        "This report was generated by BioLink, a computational drug repurposing tool. "
        "Predictions are based on knowledge graph AI and should be treated as hypotheses "
        "for further investigation, not clinical recommendations.",
    )

    return pdf.output()
